### ISSUE TITLE
Separate Git branches

### ISSUE THREAD

**Issue by lassik** [weinholt/scheme-docker#15]
Is there a particular reason that each Scheme implementation currently has its own Git branch? I noticed that within each branch the Dockerfile for that Scheme is also in a subdirectory named after that Scheme, so we could differentiate the Schemes even if all the Dockerfiles lived in the same branch.

**Comment by weinholt** [comment]
It's due to a technical limitation in Docker Hub. These were the options, afaik:

* Put everything on the same branch. Each push causes every image to be rebuilt. Expensive.
* Put everything on separate GitHub repositories. Horrible.
* Put everything on separate branches. Manageable.

They have since then improved Docker Hub a little bit. Now you can choose the build context directory, but I don't think it helps reduce the number of builds triggered by a push.

**Comment by lassik** [comment]
OK, that makes a lot of sense. I agree with your judgment.
