### ISSUE TITLE
Gauche Dockerfile

### ISSUE THREAD

**Issue by shirok** [weinholt/scheme-docker#34]
Is there a policy (base image, using deb file, being slim, etc.) for building a distribution?
I maintain a Dockerfile that pulls the newest Gauche release:
https://github.com/shirok/Gauche-docker-image

If there're requirements, I may be able to provide one.

**Comment by lassik** [comment]
Thanks for volunteering Shiro :)

Most of the existing containers are built by downloading the latest source tarball via HTTP and then running configure/make/make install (or equivalent). The current Gauche container is an exception because it just installs Gauche from Debian APT. We use `FROM debian:buster-slim` as the Linux distro. There are one or two Alpine Linux containers in there too (one for Chez at least).

**Comment by lassik** [comment]
We install the Schemes under `/usr/local` (Debian puts `/usr/local/bin` into `PATH` by default). A special command `/usr/local/bin/banner-scheme` is the Docker default command. It displays the Scheme implementation's name and version number and then starts a REPL. For Gauche we do this via`gosh -V && exec gosh "$@"`.

**Comment by lassik** [comment]
Göran also likes to have a standard command to run scripts in the container. For R7RS Schemes we have a `scheme-r7rs` command. Here's the one for Chibi: https://github.com/weinholt/scheme-docker/pull/2/files

**Comment by weinholt** [comment]
Looks like a CONTRIBUTING.md file is needed. :)

The current Gauche image is, as @lassik says, based on the Debian package. This is due to my own laziness. It would be great to update it so that the most recent versions can be provided without waiting for a new stable Debian release.

The Dockerfile should be on its own branch (to minimize the amount of builds triggered in Docker Hub). It should be based on a specific Debian version (debian:buster-slim if it will build there). It should download a specific version of the Scheme. A secure download is preferable, e.g. one that verifies the SHA256 or git hash.

My own use case for these Docker images is to run CI tests against a large variety of Schemes. So it helps if there is a standard wrapper for running Scheme programs. For R6RS we have the description in the non-normative appendix. For everyone else we have SRFI-22, so e.g. `scheme-r7rs` as @lassik said. We also have the use case that you want to run a particular Scheme interactively, and for that we install a `scheme-banner` program that starts the REPL, also printing a version banner if the REPL normally doesn't have one.

Have a look at the existing branches, there are a lot of examples.

**Comment by shirok** [comment]
Thanks, closing.
(Related https://github.com/weinholt/scheme-docker/pull/40 )
